mydogcollectorapp/my_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.Home.as_view(), name='home'),
   path('about/', views.about, name='about'),
   path('mountains/', views.mountain_index, name='mountain-index'),
   path('mountains/<int:mountain_id>/', views.mountain_detail, name='mountain-detail'),
   path('mountains/create/', views.MountainCreate.as_view(), name='mountain-create'),
   path('mountains/<int:pk>/update/', views.MountainUpdate.as_view(), name='mountain-update'),
   path('mountains/<int:pk>/delete/', views.MountainDelete.as_view(), name='mountain-delete'),
   path('mountains/<int:mountain_id>/add-climb/', views.add_climb, name='add-climb'),
   path('accounts/signup/', views.signup, name='signup'),
]

mydogcollectorapp/mydogcollectorapp/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

mydogcollectorapp/my_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User



DIFFICULTIES = (
    ('E', 'Easy'),
    ('M', 'Medium'),
    ('H', 'Hard')
)

class Mountain(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("mountain-detail", kwargs={"mountain_id": self.id})

class Climb(models.Model):
    date = models.DateField('Date Climbed')
    difficulty = models.CharField(
        max_length=1,
        choices=DIFFICULTIES,
        default=DIFFICULTIES[0][0]
     )
    
    mountain = models.ForeignKey(Mountain, on_delete=models.CASCADE)

    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_difficulty_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

mydogcollectorapp/my_app/forms.py
from django import forms
from .models import Climb

class ClimbForm(forms.ModelForm):
    class Meta:
        model = Climb
        fields = ['date', 'difficulty']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

mydogcollectorapp/my_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Mountain 
from .forms import ClimbForm



@login_required
def mountain_index(request):
    mountains = Mountain.objects.filter(user=request.user)
    return render(request, 'mountains/index.html', {'mountains': mountains})

# def home(request):
#     return render(request, 'home.html')
class Home(LoginView):
    template_name = 'home.html'

def about(request):
    return render(request, 'about.html')

@login_required
def mountain_detail(request, mountain_id):
    mountain = Mountain.objects.get(id=mountain_id)
    climb_form = ClimbForm()
    return render(request, 'mountains/detail.html', {
        'mountain': mountain, 'climb_form': climb_form})

class MountainCreate(LoginRequiredMixin, CreateView):
    model = Mountain
    fields = '__all__'

    def form_valid(self, form):
        form.instance.user = self.request.user  
        return super().form_valid(form)

class MountainUpdate(LoginRequiredMixin, UpdateView):
    model = Mountain
    fields = ['location', 'description']

class MountainDelete(LoginRequiredMixin, DeleteView):
    model = Mountain
    success_url = '/mountains/'

@login_required
def add_climb(request, mountain_id):
    # create a ModelForm instance using the data in request.POST
    form = ClimbForm(request.POST)
    # validate the form
    if form.is_valid():
        new_climb = form.save(commit=False)
        new_climb.mountain_id = mountain_id
        new_climb.save()
    return redirect('mountain-detail', mountain_id=mountain_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('mountain-index')
        else:
            error_message = 'Invalid sign up - try again'

    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

mydogcollectorapp/my_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About the Mountain Collector</h1>
<hr />
<p class="page-content">
  I love pb&J sandwiches and hiking. I want to do well on this project!
</p>
{% endblock %}

mydogcollectorapp/my_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'images/header-logo.svg' %}" />
    <title>Mountain Collector</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
        <div class="header-bar">
      <div class="header-logo-container">
        <a href="{% url 'home' %}">
          <img src="{% static 'images/header-logo.svg' %}" alt="The Mountain Collector Logo" />
        </a>
      </div>
      <nav>
        <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'mountain-index' %}">All Mountains</a></li>
          <li><a href="{% url 'mountain-create' %}">Add a Mountain</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit">Log out</button>
            </form>
          </li>
        {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}
        </ul>
      </nav>
      </div>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

mydogcollectorapp/my_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/home.css' %}"
/>
{% endblock %} {% block content %}

<section class="logo-container">
  <div class="mountain-container">
    <img
      src="{% static 'images/mountain3.svg' %}"
      alt="Snowcapped Mountain"
    />
  </div>
  <img
    src="{% static 'images/mountain2.svg' %}"
    alt="Text reads: Mountain Collector"
  />
</section>
{% if not user.is_authenticated %}
<section>
  <form action="{% url 'home' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %} {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}" />
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>
{% endif %}
{% endblock %}

mydogcollectorapp/my_app/templates/mountains/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/mountains/mountain-detail.css' %}" />
{% endblock %} 
{% block content %}
<section class="cat-container">
  <div class="cat-img">
    <img src="{% static 'images/mountain1.svg' %}" alt="A mountain" />
  </div>
  <div class="mountain-details">
    <h2 class="card-title">{{ mountain.name }}</h2>
      <h2 class="card-title">{{ mountain.location }}</h2>
      <h2 class="card-title">{{ mountain.description }}</h2>

      <div class="mountain-actions">
        <a href="{% url 'mountain-update' mountain.id %}" class="btn warn">Edit</a>
        <a href="{% url 'mountain-delete' mountain.id %}" class="btn danger">Delete</a>
      </div>
  </div>
</section>
<div class="feedings-toy-container">
    <section class="feedings">
      <div class="subsection-title">
        <h2>Climbs</h2>
        <img
          src="{% static 'images/mountain2.svg' %}"
          alt="Mountain"
        />
      </div>
      <h3>Add a Climb</h3>

<form action="{% url 'add-climb' mountain.id %}" method="post" class="subsection-content" autocomplete="off">
  {% csrf_token %} 
  {{ climb_form.as_p }}
  <button type="submit" class="btn submit">Add Climb</button>
</form>
<h3>Past Climbs</h3>
{% if mountain.climb_set.all.count %}
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Difficulty</th>
      </tr>
    </thead>
    <tbody>
      {% for climb in mountain.climb_set.all %}
      <tr>
        <td>{{climb.date}}</td>
        <td>{{climb.get_difficulty_display}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <div class="subsection-content">
    <p>⚠️ {{mountain.name}} has not been climbed!</p>
  </div>
{% endif %}
    </section>
  </div>
  
{% endblock %}

mydogcollectorapp/my_app/templates/mountains/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/mountains/mountain-index.css' %}"
/>
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Mountain List</h1>
  <img
    src="{% static 'images/mountain1.svg' %}"
    alt="A pretty mountain"
  />
  <img
    src="{% static 'images/mountain2.svg' %}"
    alt="A cold mountain"
  />
  <img
    src="{% static 'images/mountain3.svg' %}"
    alt="A mountain with snow"
  />
</section>

<section class="card-container">
  {% for mountain in mountains %}
  <div class="card">
    <a href="{% url 'mountain-detail' mountain.id %}">
    <div class="card-content">
      <div class="card-img-container">
        <img
          src="{% static 'images/mountain3.svg' %}"
          alt="Mountain"
        />
      </div>
      <h2 class="card-title">{{ mountain.name }}</h2>
      <h2 class="card-title">{{ mountain.location }}</h2>
      <h2 class="card-title">{{ mountain.description }}</h2>
    </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}

mydogcollectorapp/my_app/templates/my_app/mountain_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Mountain?</h1>
  <img src="{% static 'images/mountain3.svg' %}" alt="A mountain" />
</div>

<h2>Are you sure you want to delete {{ mountain.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'mountain-detail' mountain.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

mydogcollectorapp/my_app/templates/my_app/mountain_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
    {% if mountain %}
    <h1>Edit {{ mountain.name }}</h1>
  {% else %}
    <h1>Add a Mountain</h1>
  {% endif %}
  <img src="{% static 'images/mountain2.svg' %}" alt="A mountain" />
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

mydogcollectorapp/my_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/mountain1.svg' %}" alt="mountain" />
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}